name: opensear_worker

on:
  workflow_dispatch:
    inputs:
      tweetid:
        description: "Tweet ID from dispatch"
        required: true
        type: string

jobs:
  run_worker:
    runs-on: ubuntu-latest
    name: Run OpenSear Worker
    steps:
      - name: Setup and Run Worker
        uses: Niweera/opensear@main
        with:
          tweetid: ${{ github.event.inputs.tweetid }}
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWEETPIK_API_KEY: ${{ secrets.TWEETPIK_API_KEY }}
          METAMASK_PASSWORD: ${{ secrets.METAMASK_PASSWORD }}
          METAMASK_MNEMONIC_PHRASE: ${{ secrets.METAMASK_MNEMONIC_PHRASE }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}


